<template functional>
  <!-- Generated by graphviz version 2.40.1 (20161225.0304) -->
  <!-- Title: Elimination_3 Pages: 1 -->
  <svg preserveAspectRatio="xMidYMin meet" width="786pt" height="1084pt" viewBox="0.00 0.00 786.00 1084.00">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 1080)">
      <title>Elimination_3</title>
      <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-1080 782,-1080 782,4 -4,4" />
      <g id="clust1" class="cluster">
        <title>cluster_mainloop1</title>
      </g>
      <g id="clust2" class="cluster">
        <title>cluster_mainloop2</title>
      </g>
      <g id="clust3" class="cluster">
        <title>cluster_mainloop3</title>
      </g>
      <g id="clust4" class="cluster">
        <title>cluster_mainloop4</title>
      </g>
      <g id="clust5" class="cluster">
        <title>cluster_mainloop5</title>
      </g>
      <g id="clust6" class="cluster">
        <title>cluster_mainloop6</title>
      </g>
      <!-- 1F Apple Inn Square -->
      <g id="node1" class="node">
        <title>1F Apple Inn Square</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="154.5274,-988 21.4726,-988 21.4726,-952 154.5274,-952 154.5274,-988"
        />
        <text
          text-anchor="middle"
          x="88"
          y="-965.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F Apple Inn Square</text>
      </g>
      <!-- B4F Subway Car -->
      <g id="node2" class="node">
        <title>B4F Subway Car</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="137.4356,-916 24.5644,-916 24.5644,-880 137.4356,-880 137.4356,-916"
        />
        <text
          text-anchor="middle"
          x="81"
          y="-893.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >B4F Subway Car</text>
      </g>
      <!-- 1F Apple Inn Square&#45;&#45;B4F Subway Car -->
      <g id="edge6" class="edge">
        <title>1F Apple Inn Square--B4F Subway Car</title>
        <path fill="none" stroke="#000000" d="M81,-951.8314C81,-941 81,-927.2876 81,-916.4133" />
      </g>
      <!-- Stairwell (Underbelly) -->
      <g id="node3" class="node">
        <title>Stairwell (Underbelly)</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="158.3406,-844 15.6594,-844 15.6594,-808 158.3406,-808 158.3406,-844"
        />
        <text
          text-anchor="middle"
          x="87"
          y="-821.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Stairwell (Underbelly)</text>
      </g>
      <!-- B4F Subway Car&#45;&#45;Stairwell (Underbelly) -->
      <g id="edge7" class="edge">
        <title>B4F Subway Car--Stairwell (Underbelly)</title>
        <path fill="none" stroke="#000000" d="M81,-879.8314C81,-869 81,-855.2876 81,-844.4133" />
      </g>
      <!-- Show Animals&#39; Board House -->
      <g id="node6" class="node">
        <title>Show Animals' Board House</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="369.4656,-772 188.5344,-772 188.5344,-736 369.4656,-736 369.4656,-772"
        />
        <text
          text-anchor="middle"
          x="279"
          y="-749.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Show Animals&#39; Board House</text>
      </g>
      <!-- Stairwell (Underbelly)&#45;&#45;Show Animals&#39; Board House -->
      <g id="edge8" class="edge">
        <title>Stairwell (Underbelly)--Show Animals' Board House</title>
        <path
          fill="none"
          stroke="#000000"
          d="M158.4534,-826C180.3692,-826 198.8247,-826 198.8247,-826 198.8247,-826 198.8247,-793.498 198.8247,-772.1686"
        />
      </g>
      <!-- Path to Observation Deck -->
      <g id="node4" class="node">
        <title>Path to Observation Deck</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="369.2366,-916 208.7634,-916 208.7634,-880 369.2366,-880 369.2366,-916"
        />
        <text
          text-anchor="middle"
          x="289"
          y="-893.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Path to Observation Deck</text>
      </g>
      <!-- Path to Observation Deck&#45;&#45;1F Apple Inn Square -->
      <g id="edge3" class="edge">
        <title>Path to Observation Deck--1F Apple Inn Square</title>
        <path
          fill="none"
          stroke="#000000"
          d="M208.6464,-898C176.0192,-898 145.8655,-898 145.8655,-898 145.8655,-898 145.8655,-930.502 145.8655,-951.8314"
        />
      </g>
      <!-- 1F R.P.D. Office -->
      <g id="node5" class="node">
        <title>1F R.P.D. Office</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="344.7563,-844 233.2437,-844 233.2437,-808 344.7563,-808 344.7563,-844"
        />
        <text
          text-anchor="middle"
          x="289"
          y="-821.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F R.P.D. Office</text>
      </g>
      <!-- Path to Observation Deck&#45;&#45;1F R.P.D. Office -->
      <g id="edge4" class="edge">
        <title>Path to Observation Deck--1F R.P.D. Office</title>
        <path fill="none" stroke="#000000" d="M289,-879.8314C289,-869 289,-855.2876 289,-844.4133" />
      </g>
      <!-- B2F Passage -->
      <g id="node21" class="node">
        <title>B2F Passage</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="488.9348,-628 401.0652,-628 401.0652,-592 488.9348,-592 488.9348,-628"
        />
        <text
          text-anchor="middle"
          x="445"
          y="-605.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >B2F Passage</text>
      </g>
      <!-- Path to Observation Deck&#45;&#45;B2F Passage -->
      <g id="edge5" class="edge">
        <title>Path to Observation Deck--B2F Passage</title>
        <path
          fill="none"
          stroke="#000000"
          d="M369.3308,-898C413.5936,-898 459.6558,-898 459.6558,-898 459.6558,-898 459.6558,-691.0659 459.6558,-628.0157"
        />
      </g>
      <!-- 1F R.P.D. Office&#45;&#45;Show Animals&#39; Board House -->
      <g id="edge9" class="edge">
        <title>1F R.P.D. Office--Show Animals' Board House</title>
        <path fill="none" stroke="#000000" d="M289,-807.8314C289,-797 289,-783.2876 289,-772.4133" />
      </g>
      <!-- B6F East Passage -->
      <g id="node9" class="node">
        <title>B6F East Passage</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="735.5381,-772 620.4619,-772 620.4619,-736 735.5381,-736 735.5381,-772"
        />
        <text
          text-anchor="middle"
          x="678"
          y="-749.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >B6F East Passage</text>
      </g>
      <!-- 1F R.P.D. Office&#45;&#45;B6F East Passage -->
      <g id="edge21" class="edge">
        <title>1F R.P.D. Office--B6F East Passage</title>
        <path
          fill="none"
          stroke="#000000"
          d="M344.7342,-826C452.2962,-826 678,-826 678,-826 678,-826 678,-793.498 678,-772.1686"
        />
      </g>
      <!-- Pier -->
      <g id="node16" class="node">
        <title>Pier</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="231,-196 177,-196 177,-160 231,-160 231,-196"
        />
        <text
          text-anchor="middle"
          x="204"
          y="-173.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Pier</text>
      </g>
      <!-- Show Animals&#39; Board House&#45;&#45;Pier -->
      <g id="edge18" class="edge">
        <title>Show Animals' Board House--Pier</title>
        <path
          fill="none"
          stroke="#000000"
          d="M202.845,-735.8101C202.845,-649.5663 202.845,-282.4476 202.845,-196.1943"
        />
      </g>
      <!-- Show Animals&#39; Board House&#45;&#45;B2F Passage -->
      <g id="edge10" class="edge">
        <title>Show Animals' Board House--B2F Passage</title>
        <path
          fill="none"
          stroke="#000000"
          d="M369.6588,-754C401.891,-754 430.3442,-754 430.3442,-754 430.3442,-754 430.3442,-666.9861 430.3442,-628.2377"
        />
      </g>
      <!-- 1F Examination Room -->
      <g id="node7" class="node">
        <title>1F Examination Room</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="760.5547,-556 617.4453,-556 617.4453,-520 760.5547,-520 760.5547,-556"
        />
        <text
          text-anchor="middle"
          x="689"
          y="-533.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F Examination Room</text>
      </g>
      <!-- 1F Apartment -->
      <g id="node8" class="node">
        <title>1F Apartment</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="721.1509,-484 626.8491,-484 626.8491,-448 721.1509,-448 721.1509,-484"
        />
        <text
          text-anchor="middle"
          x="674"
          y="-461.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F Apartment</text>
      </g>
      <!-- 1F Examination Room&#45;&#45;1F Apartment -->
      <g id="edge15" class="edge">
        <title>1F Examination Room--1F Apartment</title>
        <path fill="none" stroke="#000000" d="M674,-519.8314C674,-509 674,-495.2876 674,-484.4133" />
      </g>
      <!-- B5F Main Shaft -->
      <g id="node15" class="node">
        <title>B5F Main Shaft</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="369.2176,-412 262.7824,-412 262.7824,-376 369.2176,-376 369.2176,-412"
        />
        <text
          text-anchor="middle"
          x="316"
          y="-389.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >B5F Main Shaft</text>
      </g>
      <!-- 1F Apartment&#45;&#45;B5F Main Shaft -->
      <g id="edge16" class="edge">
        <title>1F Apartment--B5F Main Shaft</title>
        <path
          fill="none"
          stroke="#000000"
          d="M674,-447.8314C674,-426.502 674,-394 674,-394 674,-394 468.9374,-394 369.2096,-394"
        />
      </g>
      <!-- Stairwell (EotR) -->
      <g id="node10" class="node">
        <title>Stairwell (EotR)</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="736.1425,-700 627.8575,-700 627.8575,-664 736.1425,-664 736.1425,-700"
        />
        <text
          text-anchor="middle"
          x="682"
          y="-677.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Stairwell (EotR)</text>
      </g>
      <!-- B6F East Passage&#45;&#45;Stairwell (EotR) -->
      <g id="edge22" class="edge">
        <title>B6F East Passage--Stairwell (EotR)</title>
        <path
          fill="none"
          stroke="#000000"
          d="M681.8487,-735.8314C681.8487,-725 681.8487,-711.2876 681.8487,-700.4133"
        />
      </g>
      <!-- University Sewers (left) -->
      <g id="node11" class="node">
        <title>University Sewers (left)</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="762.5002,-628 611.4998,-628 611.4998,-592 762.5002,-592 762.5002,-628"
        />
        <text
          text-anchor="middle"
          x="687"
          y="-605.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >University Sewers (left)</text>
      </g>
      <!-- Stairwell (EotR)&#45;&#45;University Sewers (left) -->
      <g id="edge23" class="edge">
        <title>Stairwell (EotR)--University Sewers (left)</title>
        <path fill="none" stroke="#000000" d="M682,-663.8314C682,-653 682,-639.2876 682,-628.4133" />
      </g>
      <!-- University Sewers (left)&#45;&#45;1F Examination Room -->
      <g id="edge24" class="edge">
        <title>University Sewers (left)--1F Examination Room</title>
        <path fill="none" stroke="#000000" d="M689,-591.8314C689,-581 689,-567.2876 689,-556.4133" />
      </g>
      <!-- University Sewers (right) -->
      <g id="node12" class="node">
        <title>University Sewers (right)</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="395.2851,-340 236.7149,-340 236.7149,-304 395.2851,-304 395.2851,-340"
        />
        <text
          text-anchor="middle"
          x="316"
          y="-317.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >University Sewers (right)</text>
      </g>
      <!-- B1F Parking Garage -->
      <g id="node13" class="node">
        <title>B1F Parking Garage</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="381.5786,-268 250.4214,-268 250.4214,-232 381.5786,-232 381.5786,-268"
        />
        <text
          text-anchor="middle"
          x="316"
          y="-245.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >B1F Parking Garage</text>
      </g>
      <!-- University Sewers (right)&#45;&#45;B1F Parking Garage -->
      <g id="edge26" class="edge">
        <title>University Sewers (right)--B1F Parking Garage</title>
        <path fill="none" stroke="#000000" d="M316,-303.8314C316,-293 316,-279.2876 316,-268.4133" />
      </g>
      <!-- Linda Sewers -->
      <g id="node14" class="node">
        <title>Linda Sewers</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="395.0823,-196 302.9177,-196 302.9177,-160 395.0823,-160 395.0823,-196"
        />
        <text
          text-anchor="middle"
          x="349"
          y="-173.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Linda Sewers</text>
      </g>
      <!-- B1F Parking Garage&#45;&#45;Linda Sewers -->
      <g id="edge17" class="edge">
        <title>B1F Parking Garage--Linda Sewers</title>
        <path
          fill="none"
          stroke="#000000"
          d="M342.1243,-231.8314C342.1243,-221 342.1243,-207.2876 342.1243,-196.4133"
        />
      </g>
      <!-- 1F Hospital Hall -->
      <g id="node17" class="node">
        <title>1F Hospital Hall</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="340.8231,-124 231.1769,-124 231.1769,-88 340.8231,-88 340.8231,-124"
        />
        <text
          text-anchor="middle"
          x="286"
          y="-101.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F Hospital Hall</text>
      </g>
      <!-- Linda Sewers&#45;&#45;1F Hospital Hall -->
      <g id="edge27" class="edge">
        <title>Linda Sewers--1F Hospital Hall</title>
        <path
          fill="none"
          stroke="#000000"
          d="M321.6853,-159.8314C321.6853,-149 321.6853,-135.2876 321.6853,-124.4133"
        />
      </g>
      <!-- B5F Main Shaft&#45;&#45;University Sewers (right) -->
      <g id="edge25" class="edge">
        <title>B5F Main Shaft--University Sewers (right)</title>
        <path fill="none" stroke="#000000" d="M316,-375.8314C316,-365 316,-351.2876 316,-340.4133" />
      </g>
      <!-- Pier&#45;&#45;1F Hospital Hall -->
      <g id="edge19" class="edge">
        <title>Pier--1F Hospital Hall</title>
        <path
          fill="none"
          stroke="#000000"
          d="M231.1107,-178C238.0821,-178 243.6592,-178 243.6592,-178 243.6592,-178 243.6592,-145.498 243.6592,-124.1686"
        />
      </g>
      <!-- Room 206 -->
      <g id="node18" class="node">
        <title>Room 206</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="323.2277,-52 248.7723,-52 248.7723,-16 323.2277,-16 323.2277,-52"
        />
        <text
          text-anchor="middle"
          x="286"
          y="-29.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Room 206</text>
      </g>
      <!-- 1F Hospital Hall&#45;&#45;Room 206 -->
      <g id="edge20" class="edge">
        <title>1F Hospital Hall--Room 206</title>
        <path fill="none" stroke="#000000" d="M286,-87.8314C286,-77 286,-63.2876 286,-52.4133" />
      </g>
      <!-- J&#39;s Bar -->
      <g id="node19" class="node">
        <title>J's Bar</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="316.7622,-1060 261.2378,-1060 261.2378,-1024 316.7622,-1024 316.7622,-1060"
        />
        <text
          text-anchor="middle"
          x="289"
          y="-1037.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >J&#39;s Bar</text>
      </g>
      <!-- 1F Doctor&#39;s Office -->
      <g id="node20" class="node">
        <title>1F Doctor's Office</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="350.0088,-988 227.9912,-988 227.9912,-952 350.0088,-952 350.0088,-988"
        />
        <text
          text-anchor="middle"
          x="289"
          y="-965.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >1F Doctor&#39;s Office</text>
      </g>
      <!-- J&#39;s Bar&#45;&#45;1F Doctor&#39;s Office -->
      <g id="edge1" class="edge">
        <title>J's Bar--1F Doctor's Office</title>
        <path
          fill="none"
          stroke="#000000"
          d="M289,-1023.8314C289,-1013 289,-999.2876 289,-988.4133"
        />
      </g>
      <!-- 1F Doctor&#39;s Office&#45;&#45;Path to Observation Deck -->
      <g id="edge2" class="edge">
        <title>1F Doctor's Office--Path to Observation Deck</title>
        <path fill="none" stroke="#000000" d="M289,-951.8314C289,-941 289,-927.2876 289,-916.4133" />
      </g>
      <!-- B2F Passage&#45;&#45;1F Examination Room -->
      <g id="edge14" class="edge">
        <title>B2F Passage--1F Examination Room</title>
        <path
          fill="none"
          stroke="#000000"
          d="M489.1203,-610C528.0389,-610 578.6133,-610 578.6133,-610 578.6133,-610 578.6133,-538 578.6133,-538 578.6133,-538 596.1374,-538 617.2212,-538"
        />
      </g>
      <!-- B2F Passage&#45;&#45;B1F Parking Garage -->
      <g id="edge12" class="edge">
        <title>B2F Passage--B1F Parking Garage</title>
        <path
          fill="none"
          stroke="#000000"
          d="M401.0244,-616C334.7477,-616 216.9225,-616 216.9225,-616 216.9225,-616 216.9225,-250 216.9225,-250 216.9225,-250 231.8897,-250 250.1895,-250"
        />
      </g>
      <!-- B2F Passage&#45;&#45;B5F Main Shaft -->
      <g id="edge13" class="edge">
        <title>B2F Passage--B5F Main Shaft</title>
        <path
          fill="none"
          stroke="#000000"
          d="M400.9663,-604C363.596,-604 316,-604 316,-604 316,-604 316,-463.3605 316,-412.2688"
        />
      </g>
      <!-- Locker Room (Flashback) -->
      <g id="node22" class="node">
        <title>Locker Room (Flashback)</title>
        <polygon
          fill="none"
          stroke="#000000"
          points="545.4524,-556 382.5476,-556 382.5476,-520 545.4524,-520 545.4524,-556"
        />
        <text
          text-anchor="middle"
          x="464"
          y="-533.8"
          font-family="Times,serif"
          font-size="14.00"
          fill="#000000"
        >Locker Room (Flashback)</text>
      </g>
      <!-- B2F Passage&#45;&#45;Locker Room (Flashback) -->
      <g id="edge11" class="edge">
        <title>B2F Passage--Locker Room (Flashback)</title>
        <path fill="none" stroke="#000000" d="M445,-591.8314C445,-581 445,-567.2876 445,-556.4133" />
      </g>
    </g>
  </svg>
</template>

<script>
export default {
  name: 'elimination-3',
};
</script>
